### ISSUE TITLE
Unique name for Templates

### ISSUE THREAD

**Issue by Elorfin** [InnovaLangues/PathBundle#119]
Check if name is unique before saving a Template

**Comment by taniamcnamara** [comment]
@Elorfin parle-t-on du modèle de parcours? si oui à repasser en P1

**Comment by Elorfin** [comment]
oui. 
Nathalie a créé un nouveau ticket sur l'ENPA pour le suivi. Ce ticket n'a donc plus raison d'être.

Innovalangues/ENPA#247
