### ISSUE TITLE
bug : Problem when adding ressource to a path

### ISSUE THREAD

**Issue by stmolivier** [InnovaLangues/PathBundle#252]
On claroline 4.2.2, logged as a teacher, i create a path.
Whe i want to add an activity or any ressource for a step, i have a js error :
```
Uncaught Error: Unknown picker "picker-activity"		libraries.js:86 
manager.picker									ibraries.js:86 
link.$scope.resourcePickerOpen					angular-ui.js:93
 link.el.(anonymous function).onclick					angular-ui.js:93
```

and i also have other errors : 
```
GET http://claroline4-i1/web/app_dev.php/resource/manager_parameters 401 (Unauthorized) jquery-2.1.0.min.js:4 
o.ajaxTransport.l.cors.a.crossDomain.send   jquery-2.1.0.min.js:4 
o.extend.ajax                           jquery-2.1.0.min.js:4 
server.fetchManagerParameters           libraries.js:82 
fetchMissingParameters                  libraries.js:96 
manager.createPicker                    libraries.js:85 
```

What could be the cause. I work localhost, with local resources, so i dont understand the cross domain error.

PS :  just to be sure rights where not the issue, i tried also to chmod ALL my Claroline to 777 but no change.
PS: the other js stuff work : i can add substep...

**Comment by Elorfin** [comment]
I have just tested and I don't reproduce your bug.
I work locally too and I don't think this is your problem.

After installation do you have : 
* Clear the cache with `php app/console cache:clear`
* Publish public assets with `php app/console assets:install --symlink`
* Rebuild assets with `php app/console assetic:dump`
* Empty your browser cache

You can also try to upgrade your version of CoreBundle to 4.4.0 (which is the one I have installed).

If this doesn't work : when does this error appear ? When you try to open the resource picker (and so the picker doesn't open) or when you try to pick a resource ?

**Comment by stmolivier** [comment]
Thank you for the answer.
I've tried all the steps you suggest but i still have this error.

My version is 4.2.2 (i installed a Claroline 3 days ago, from https://github.com/claroline/Claroline )
I'll try to updgrade.

To be precise:
I'm logged as a teacher. 
* I go into a workspace, 
* i choose the Tool ressources. 
* I select (click) the path ressource. 
* I clic on Edit (i created it previously)
* when the path page loads, i have in my console (before i click on anything) : 
several (3 times, but maybe the number is not relevant) times  the js error : 
```
GET http://claroline4-i1/web/app_dev.php/resource/manager_parameters 401 (Unauthorized) jquery-2.1.0.min.js:4 
```
and then 
* if i click on select an activity icon (the folder next to the step name) i've got the error : 
```
Uncaught Error: Unknown picker "picker-activity"        libraries.js:86 
```
* if i click on select an primary ressource button i've got the error : 
```
Uncaught Error: Unknown picker "picker-primary-resource"        libraries.js:86 
```
* if i click on select an secondary ressource button i've got the error : 
```
Uncaught Error: Unknown picker "picker-secondary-resource"        libraries.js:86 
```
