### ISSUE TITLE
Additional installer is not compatible with core >=4.5

### ISSUE THREAD

**Issue by stefk** [InnovaLangues/PathBundle#256]
A fresh install produces the following fatal error:

>>> Access level to Innova\PathBundle\Installation\AdditionalInstaller::$logger must be protected (as in class Claroline\InstallationBundle\Additional\AdditionalInstaller) or weaker in /home/skl@ecam.be/projets/claronext/vendor/innova/path-bundle/Innova/PathBundle/Installation/AdditionalInstaller.php on line 68

**Comment by Elorfin** [comment]
Available in v4.0.6.
We have merged pull request from @maxailloud : #254.
