### ISSUE TITLE
Improvement : add a full screen functionnality or a bigger ressource player iframe or a resizable one

### ISSUE THREAD

**Issue by CPASimUSante** [InnovaLangues/PathBundle#293]
For resources like website, the height is way too small. 
![player](https://cloud.githubusercontent.com/assets/14015697/10938716/a75e2e06-82fc-11e5-8a0a-7ddfd220ff9b.png)

**Comment by Elorfin** [comment]
You can now specify the min height of the Resource in the Editor (in the properties of the Step).

I keep the issue opened for the full screen features.

**Comment by purplefish32** [comment]
This issue was moved to claroline/Claroline#736
